export const snakePuns = [
  'Why don’t snakes drink coffee? Because it makes them viperactive.',
  'What do snakes use to clean their car windows? Windscreen vipers.',
  'What is a snake’s favorite TV show? Monty Python.',
  'What do you call a snake that builds things? A boa constructor.',
  'How do venomous snakes kill their prey? In cold blood.',
  'What do you get if you cross two snakes with a magic spell? Addercadabra and abradacobra.',
  'How does a snake shoot something? With a boa and arrow.',
  'What do you get if you cross a bag of snakes and a cupboard of food? Snakes and Larders.',
  'What do you call a snake that bakes? A pie-thon.',
  'What do you call a funny snake? Hissssssterical.',
  'What do married snakes have on their bath towels? “Hiss,” and “Herss.”',
  'Why are snakes so hard to fool? They have no legs to pull.',
  'Why was the snake mad at the jewel thief? Because he wanted his diamondback.',
  'Which snake is a member of a rock band? A rattlesnake.',
  'What do you give a sick snake? Asp-rin.',
  'How can you rescue a snake that looks dead? With mouse-to-mouth resuscitation.',
  'What do you call a snake who works for the government? A civil serpent.',
  'What did the Mommy snake say to the Baby snake? “Please stop crying and viper your nose.”',
  'Why did the snake cross the road? To get to the other ssssssssside.',
  'Who is a snake’s favorite author? William Snakespeare.',
  'What type of snake does a baby like to play with? A rattlesnake.',
  'A snake walks into a bar. The bartender says, “How did you do that?”',
  'Why do snakes always measure in inches? Because they don’t have feet.',
  'What did the snake give her boyfriend? A goodnight hiss.',
  'What did the snake say to the loud children at the library? “Ssssss.”',
  'What do you get when you cross a snake and a plane? A Boeing constrictor.',
  'What is another word for a python? A mega-bite.',
  'What do you call an important English snake? Sir Pent.',
  'Why should you never use a snake as a boomerang? Because it will always come back to bite you.',
  'What’s a snake’s favorite dance? The snake, rattle, and roll.',
  'What do snakes do when they get angry? They throw hissy fits.',
  'What is a snake’s favorite school subject? Hisstory.',
  'Nobody wants to listen to White Snake with me. So here I go again on my own.',
  'A sheep, a drum, and a snake fell off a cliff. Bah-dum-tiss.',
  'What do you get when you cross a rabbit with a snake? A jump rope.',
  'Why can’t a snake rob a bank? Because they are unarmed.',
  'A drum set and a snake falls off a cliff. The drummer and pet shop owner are very sad now.',
  'After the flood, satisfied his work was done, Noah was inspecting the ark one last time when he came across a pair of snakes. “Why are you still here?” he asked in surprise. “It’s safe now. Go forth! And multiply!” The snakes stared at him in confusion.“But… we’re adders.”',
  'A jellyfish, a snake, and a snail walk into a bar. The jellyfish says, “This is impossible.”',
  'What do you call a snake that’s 3.14 meters long? A “Pi”-thon.',
  'My girlfriend is a snake. Whenever you ask her whose fault was it, she goes “HISSSSSSSSSS.”',
  'Doctor: “Can you describe the snake that bit you?” Patient: “Yes. It looked like an angry rope.”',
  'I got mugged by a cobra once when I was walking through the park. I wouldn’t recognize it again, though. It was wearing a hood.',
  'A Boy Scout asks his scout leader, “Sir, is this snake poisonous?” The scout leader looks at it and says, “No, that snake’s not poisonous at all.” So the boy picks up the snake, which bites him. The boy starts to spasm and foam at the mouth as the other kids look on in horror. The scout leader says, “But that snake is venomous. Poison is ingested or absorbed, while venom is injected. Let’s get it right next time, boys.”',
  'What kind of letters did the snake get from his admirers? Fang letters.',
  'What do you get if you cross a newborn snake with a basketball? A bouncing baby boa.',
  'Why should you never weigh a snake? They have their own scales.',
  'What do you call a snake that’s shed its skin? Snaked.',
  'What’s a snake’s favorite dance? The mamba.',
  'Why did Woody have to wear sneakers? There was a snake in his boot.',
  'What kind of car does a snake drive? An ana-honda.',
];
